config/routes.rb
Rails.application.routes.draw do
  get 'libr_rel_amigos/new'

  get 'libr_rel_amigos/create'

  get 'libr_rel_amigos/destroy'

  get 'libr_rel_amigos/update'

  resources :libr_rel_lib_usrs

  resources :libr_usuarios

  resources :libr_libros
    resources :sessions  

  get 'funcionamiento' => 'welcomee#funcionamiento'
  get 'preguntas' => 'welcomee#preguntas'
  get 'principios' => 'welcomee#principios'
  get 'contacto' => 'welcomee#contacto'

  

  get 'login' => 'sessions#new'
  get "log_out" => "sessions#destroy", :as => "log_out"

  get 'portada' => 'portada#inicio'
  get 'contenido' => 'portada#contenido'
  

  get 'libronuevo' => 'portada#libronuevo'

get 'cuentacreada' => 'libr_usuarios#cuentacreada'

  root 'welcomee#index'

end

app/controllers/welcomee_controller.rb
class WelcomeeController < ApplicationController

  def index
    
  end

  def login
  end
  

end

app/helpers/welcomee_helper.rb
module WelcomeeHelper
end

app/views/welcomee/contacto.html.erb
<body>
<div id="cabecera">

    <div id="cabsup">
        <div id="logo">
            <br>
        <IMG SRC="logo.png" ALT="La primera biblioteca física p2p" WIDTH=300 HEIGHT=100% >

        </div>

        <div id="login">
        <br>
        <%= link_to 'Accede a tu cuenta', login_path %>
        <%= link_to 'Regístrate', new_libr_usuario_path %>
        </div>
    </div>


    <div id="menu">

     <ul>
        <li><%= link_to 'Inicio', root_path %></li>
        <li><%= link_to '¿Cómo funciona?', funcionamiento_path %></li>
        <li><%= link_to 'Preguntas Frecuentes', preguntas_path %></li>
        <li><%= link_to 'Nuestros principios', principios_path %></li>
        <li><%= link_to 'Contacto', contacto_path %></li>
     </ul>

    </div>

</div>
<br>
<br>
<br>
<div id="principal">

	<div id="princip_izda">
	<center>
    <IMG SRC="owl-158417.png" ALT="La primera biblioteca física p2p"
     WIDTH=278 HEIGHT=100% ALIGN=middl>
     </center>
	</div>




	<div id="princip_dcha">

<h1>Contacta con nosotros </h1> 
<br>
libreteka@openmailbox.org <br>
carlos.gonzalez@openmailbox.org





	</div>





</div>

</body>

app/views/welcomee/funcionamiento.html.erb
<body>

<div id="cabecera">

	<div id="cabsup">
		<div id="logo">
			<br>
		<IMG SRC="logo.png" ALT="La primera biblioteca física p2p" WIDTH=300 HEIGHT=100% >

		</div>

		<div id="login">
		<br>
		<%= link_to 'Accede a tu cuenta', login_path %>
		<%= link_to 'Regístrate', new_libr_usuario_path %>
		</div>
	</div>


	<div id="menu">

	 <ul>
	    <li><%= link_to 'Inicio', root_path %></li>
	    <li><%= link_to '¿Cómo funciona?', funcionamiento_path %></li>
	    <li><%= link_to 'Preguntas Frecuentes', preguntas_path %></li>
	    <li><%= link_to 'Nuestros principios', principios_path %></li>
	    <li><%= link_to 'Contacto', contacto_path %></li>
	 </ul>

	</div>

</div>
<br>
<br>
<br>
<div id="principal">

	<div id="princip_izda">
	<center>
    <IMG SRC="owl-158417.png" ALT="La primera biblioteca física p2p"
     WIDTH=278 HEIGHT=100% ALIGN=middl>
     </center>
	</div>




	<div id="princip_dcha">

<h1>Funcionamiento</h1>
<br>

Se trata de una red de gestión de préstamos entre la gente que tienes a tu alrededor. Ya sea para intercambiar objetos con tus amigos o para prestar a los vecinos de tu barrio, pueblo, o con quien tu selecciones que deseas compartir cada objeto.
<br><br>

A diferencia de otras redes sociales que te acercan a quien tienes lejos pero te alejan de aquellos que tienes cerca, esta red de intercambio te acerca a quien tienes cerca y ayuda a crear lazos entre familiares, vecinos o ciudadanos con los que tienes cosas en común.
<br><br>
La página cuenta con un gestor de préstamos donde tu puedes seleccionar el tiempo y las condiciones en las que deseas que se realice el préstamo. Y además te notificará cuando el préstamos se esté terminando para que tus objetos no se pierdan.
<br><br>
Esperemos que le saques mucho partido a la red, y recuerda que lo más importante es que tu generes tu lista de objetos para prestar.



<h4><%= link_to '¿Eres nuevo? Regístrate.', new_libr_usuario_path %></h4>


<h4><%= link_to '¿Eres habitual por aquí? Accede a tu cuenta.', login_path %></h4>



	</div>





</div>

</body>

app/views/welcomee/index.html.erb
<body>

<div id="cabecera">

	<div id="cabsup">
		<div id="logo">
			<br>
		<IMG SRC="logo.png" ALT="La primera biblioteca física p2p" WIDTH=300 HEIGHT=100% >

		</div>

		<div id="login">
		<br>
		<%= link_to 'Accede a tu cuenta', login_path %>
		<%= link_to 'Regístrate', new_libr_usuario_path %>
		</div>
	</div>


	<div id="menu">


	 <ul>
	    <li><%= link_to 'Inicio', root_path %></li>
	    <li><%= link_to '¿Cómo funciona?', funcionamiento_path %></li>
	    <li><%= link_to 'Preguntas Frecuentes', preguntas_path %></li>
	    <li><%= link_to 'Nuestros principios', principios_path %></li>
	    <li><%= link_to 'Contacto', contacto_path %></li>
	 </ul>

	</div>

</div>




<br>
<br>
<br>
<div id="principal">

	<div id="princip_izda">
	<center>
    <IMG SRC="owl-158417.png" ALT="La primera biblioteca física p2p"
     WIDTH=278 HEIGHT=100% ALIGN=middl>
     </center>
	</div>




	<div id="princip_dcha">
		<p id="notice"><%= notice %></p>

		<h1>Accede</h1>
		<br>

		<h4><%= link_to '¿Eres nuevo? Regístrate.', new_libr_usuario_path %></h4>
		<br>

		<h4><%= link_to '¿Eres habitual por aquí? Accede a tu cuenta.', login_path %></h4>


	</div>





</div>

</body>

app/views/welcomee/login.html.erb
<body>

<div id="cabecera">

	<div id="cabsup">
		<div id="logo">
		<br>
		<IMG SRC="logo.png" ALT="La primera biblioteca física p2p" WIDTH=300 HEIGHT=100% >

		</div>

		<div id="login">
		<br>
		<%= link_to 'Accede a tu cuenta', login_path %>
		<%= link_to 'Regístrate', new_libr_usuario_path %>
		</div>
	</div>


	<div id="menu">

	 <ul>
	    <li><%= link_to 'Inicio', root_path %></li>
	    <li><%= link_to '¿Cómo funciona?', funcionamiento_path %></li>
	    <li><%= link_to 'Preguntas Frecuentes', preguntas_path %></li>
	    <li><%= link_to 'Nuestros principios', principios_path %></li>
	    <li><%= link_to 'Contacto', contacto_path %></li>
	 </ul>

	</div>

</div>




<br>
<br>
<br>
<div id="principal">

	<div id="princip_izda">
	<center>
    <IMG SRC="owl-158417.png" ALT="La primera biblioteca física p2p"
     WIDTH=278 HEIGHT=100% ALIGN=middl>
     </center>
	</div>




	<div id="princip_dcha">


<h1>¿¿Otra vez tu por aquí??</h1>

<%= form_tag session_path do %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email, params[:email] %>
  </div>
  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
  </div>
  <div class="actions"><%= submit_tag "Log in" %></div>
<% end %>

	</div>





</div>

</body>

app/views/welcomee/preguntas.html.erb
<body>

<div id="cabecera">

    <div id="cabsup">
        <div id="logo">
            <br>
        <IMG SRC="logo.png" ALT="La primera biblioteca física p2p" WIDTH=300 HEIGHT=100% >

        </div>

        <div id="login">
        <br>
        <%= link_to 'Accede a tu cuenta', login_path %>
        <%= link_to 'Regístrate', new_libr_usuario_path %>
        </div>
    </div>


    <div id="menu">

     <ul>
        <li><%= link_to 'Inicio', root_path %></li>
        <li><%= link_to '¿Cómo funciona?', funcionamiento_path %></li>
        <li><%= link_to 'Preguntas Frecuentes', preguntas_path %></li>
        <li><%= link_to 'Nuestros principios', principios_path %></li>
        <li><%= link_to 'Contacto', contacto_path %></li>
     </ul>

    </div>

</div>
<br>
<br>
<br>
<div id="principal">

	<div id="princip_izda">
	<center>
    <IMG SRC="owl-158417.png" ALT="La primera biblioteca física p2p"
     WIDTH=278 HEIGHT=100% ALIGN=middl>
     </center>
	</div>




	<div id="princip_dcha">

<h1>Preguntas Frecuentes</h1>
<br>

<h3>¿Qué tal vas con la página esa que querías hacer?</h3>
Por ahora estoy aprendiendo a hacer páginas webs, que yo pensaba que era más fácil, pero al final tiene su intríngulis.

<h3>¿Cuando vas a ponerla en internet para que podamos ver lo que llevas hecho?</h3>
Aún ni lo pienso.



	</div>





</div>

</body>

app/views/welcomee/principios.html.erb
<body>
<div id="cabecera">

    <div id="cabsup">
        <div id="logo">
            <br>
        <IMG SRC="logo.png" ALT="La primera biblioteca física p2p" WIDTH=300 HEIGHT=100% >

        </div>

        <div id="login">
        <br>
        <%= link_to 'Accede a tu cuenta', login_path %>
        <%= link_to 'Regístrate', new_libr_usuario_path %>
        </div>
    </div>


    <div id="menu">

     <ul>
        <li><%= link_to 'Inicio', root_path %></li>
        <li><%= link_to '¿Cómo funciona?', funcionamiento_path %></li>
        <li><%= link_to 'Preguntas Frecuentes', preguntas_path %></li>
        <li><%= link_to 'Nuestros principios', principios_path %></li>
        <li><%= link_to 'Contacto', contacto_path %></li>
     </ul>

    </div>

</div>
<br>
<br>
<br>
<div id="principal">

	<div id="princip_izda">
	<center>
    <IMG SRC="owl-158417.png" ALT="La primera biblioteca física p2p"
     WIDTH=278 HEIGHT=100% ALIGN=middl>
     </center>
	</div>




	<div id="princip_dcha">

<h1>Estos son nuestros principios... </h1> 
<br>



Este proyecto nace desde de la corriente del software libre, y está enfocado para aplicar esa filosofía a la vida real. Para compartir trabajo y conocimiento al nivel de ciudades, pueblos, barrios o familias. Y así compartir un libro o un disco de música, pero también una opinión o una recomendación entre las personas que intercambian, que obviamente se tendrán que ver AFK (siglas en inglés de 'más allá del teclado').

<br><br>

Este proyecto nace desde la crítica al consumo infinito, y se materializa como herramienta para acabar con tantos gastos, que no son solo gastos para el bolsillo si no para el planeta.

<br><br>


Este proyecto nace desde la crítica a un modelo de comercio del arte y conocimiento, donde editoriales, discográficas y productaras ejercen de lobbie ante gobiernos obedientes, e intentan hacer del intercambio y difusión un problema o incluso un delito. 

<br><br>


Este proyecto nace desde la crítica a aquellos que visibilizan el ahorro de recursos como un perjucio económico y quiere hacer incapié en que el problema no es del intercambio sino del modelo.

<br><br>


Este proyecto nace desde la crítica a las redes sociales que venden vidas felices, cuerpos sexys, fotos de viajes vacías, o discursos políticos caducos y se materializa en nuevas redes de intercambio al nivel terrenal. Donde tengan cabida las necesidades de la gente o el intercambio intelectual.

<br><br>


Este proyecto nace desde la necesidad de organizar internet.

<br><br>


Este proyecto no otro más del estilo startup, de algún típico informático que sueña con forrarse. Obedece más bien a la necesidad innata del ser humano de hacer algo por los demás. 

<br><br>

Este proyecto se financiará por donaciones y las únicas personas que reciban dinero del proyecto serán las encargadas del mantenimiento (en caso de haberlas).

 <h1> ...si no te gustan tenemos otros.</h1>

El proyecto es libre, y cualquier persona es libre de utilizarlo de modo que se le ocurra. El propósito es avanzar hacia una mayor libertad de gestión del usuario para que de verdad sea libre y cada uno pueda adaptarlo a sus necesidades u ocurrencias.

<br><br>
Lo expuesto anteriormente son solo los principios por los que nace, pero la razón de ser se la aportará el usuario.


	</div>





</div>

</body>