config/routes.rb
Rails.application.routes.draw do
  get 'libr_rel_amigos/new'

  get 'libr_rel_amigos/create'

  get 'libr_rel_amigos/destroy'

  get 'libr_rel_amigos/update'

  resources :libr_rel_lib_usrs

  resources :libr_usuarios

  resources :libr_libros
    resources :sessions  

  get 'funcionamiento' => 'welcomee#funcionamiento'
  get 'preguntas' => 'welcomee#preguntas'
  get 'principios' => 'welcomee#principios'
  get 'contacto' => 'welcomee#contacto'

  

  get 'login' => 'sessions#new'
  get "log_out" => "sessions#destroy", :as => "log_out"

  get 'portada' => 'portada#inicio'
  get 'contenido' => 'portada#contenido'
  

  get 'libronuevo' => 'portada#libronuevo'

get 'cuentacreada' => 'libr_usuarios#cuentacreada'

  root 'welcomee#index'

end

app/models/libr_usuario.rb
class LibrUsuario < ActiveRecord::Base
	has_secure_password
	has_many :LibrRelLibUsrs, dependent: :destroy
	#has_many :LibrRelAmigo, dependent: :destroy

	has_one :libr_rel_amigo, dependent: :destroy
	accepts_nested_attributes_for :libr_rel_amigo

	validates_presence_of :Nombre
	validates_presence_of :email
	validates_presence_of :password, :on => :create
  #validates_presence_of :password_confirmation, :on => :create



 validates :password, presence: true, :if => :validate_password?

 validates :password_confirmation, presence: true, :if => :validate_password?

def validate_password?
  password_digest.present? || password_confirmation.present?
end






	# Validamos en una expresion regular nuestro email
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, format: { :with => VALID_EMAIL_REGEX , message: "El formato del correo es invalido" }
 	# Validamos que el email sea unico
 	validates :email, uniqueness: {case_sensitive: false ,message: "ya esta registrado"}


	# Validamos que el nombre tenga entre 8 a 12 caracteres
	validates :Nombre, length: { in: 1..12 , message: "debe tener entre 1 y 12 caracteres"}



  # Validamos que la contraseña tenga entre 8 a 12 caracteres
  #validates :password_digest, length: { in: 8..12 , message: "La contraseña debe tener entre 8 y 12 caracteres"}

end

app/controllers/libr_usuarios_controller.rb
class LibrUsuariosController < ApplicationController
  before_action :set_libr_usuario, only: [:show, :edit, :update, :destroy]

  # GET /libr_usuarios
  # GET /libr_usuarios.json
  def index
    @libr_usuarios = LibrUsuario.all
  end

  # GET /libr_usuarios/1
  # GET /libr_usuarios/1.json
  def show
  end

  # GET /libr_usuarios/new
  def new
    @libr_usuario = LibrUsuario.new
    @libr_usuario.build_libr_rel_amigo
  end

  # GET /libr_usuarios/1/edit
  def edit
  end

  # POST /libr_usuarios
  # POST /libr_usuarios.json
  def create
    @libr_usuario = LibrUsuario.new(libr_usuario_params)

      if @libr_usuario.save
        redirect_to cuentacreada_path, :notice => "Dentro!!!"
      else
        render "new"
      end
  end





  # PATCH/PUT /libr_usuarios/1
  # PATCH/PUT /libr_usuarios/1.json
  def update
    respond_to do |format|
      if @libr_usuario.update(libr_usuario_params)
        format.html { redirect_to @libr_usuario, notice: 'Libr usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @libr_usuario }
      else
        format.html { render :edit }
        format.json { render json: @libr_usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libr_usuarios/1
  # DELETE /libr_usuarios/1.json
  def destroy
    @libr_usuario.destroy
    respond_to do |format|
      format.html { redirect_to libr_usuarios_url, notice: 'Libr usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_libr_usuario
      @libr_usuario = LibrUsuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def libr_usuario_params
      params.require(:libr_usuario).permit(:Nombre, :Apellido1, :Apellido2, :poblacion, :email, :password, :password_confirmation,libr_rel_amigo_attributes: [:amigos_string, :amigos_integer])
    end

    
end

app/helpers/libr_usuarios_helper.rb
module LibrUsuariosHelper
end

app/views/libr_usuarios/_form.html.erb
<%= form_for(@libr_usuario) do |f| %>
  <% if @libr_usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@libr_usuario.errors.count, "error") %> prohibited this libr_usuario from being saved:</h2>

      <ul>
      <% @libr_usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Nombre %><br>
    <%= f.text_field :Nombre %>
  </div>
  <div class="field">
    <%= f.label :Apellido1 %><br>
    <%= f.text_field :Apellido1 %>
  </div>
  <div class="field">
    <%= f.label :Apellido2 %><br>
    <%= f.text_field :Apellido2 %>
  </div>
  <div class="field">
    <%= f.label :poblacion %><br>
    <%= f.text_field :poblacion %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>



  <div class="actions">
      <%= f.submit "Registrarme" %>
  </div>
<% end %>

app/views/libr_usuarios/cuentacreada.html.erb
<body>

<div id="cabecera">

	<div id="cabsup">
		<div id="logo">
		<br>
		<IMG SRC="logo.png" ALT="La primera biblioteca física p2p" WIDTH=300 HEIGHT=100% >

		</div>

		<div id="login">
		<br>
		<%= link_to 'Accede a tu cuenta', login_path %>
		<%= link_to 'Regístrate', new_libr_usuario_path %>
		</div>
	</div>


	<div id="menu">

	 <ul>
	    <li><%= link_to 'Inicio', root_path %></li>
	    <li><%= link_to '¿Cómo funciona?', funcionamiento_path %></li>
	    <li><%= link_to 'Preguntas Frecuentes', preguntas_path %></li>
	    <li><%= link_to 'Nuestros principios', principios_path %></li>
	    <li><%= link_to 'Contacto', contacto_path %></li>
	 </ul>

	</div>

</div>




<br>
<br>
<br>
<div id="principal">

	<div id="princip_izda">
	<center>
    <IMG SRC="owl-158417.png" ALT="La primera biblioteca física p2p"
     WIDTH=278 HEIGHT=100% ALIGN=middl>
     </center>
	</div>




	<div id="princip_dcha">

		<h2>Cuenta creada de puta madre.</h2>

		<h3>Ahora haz como que miras tu correo para confirmar tu dirección de correo electrónico y ya puedes acceder a tu cuenta.</h3>





</div>

</body>

app/views/libr_usuarios/edit.html.erb
<h1>Editing Libr Usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @libr_usuario %> |
<%= link_to 'Back', libr_usuarios_path %>

app/views/libr_usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Libr Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido1</th>
      <th>Apellido2</th>
      <th>Poblacion</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @libr_usuarios.each do |libr_usuario| %>
      <tr>
        <td><%= libr_usuario.Nombre %></td>
        <td><%= libr_usuario.Apellido1 %></td>
        <td><%= libr_usuario.Apellido2 %></td>
        <td><%= libr_usuario.poblacion %></td>
        <td><%= libr_usuario.email %></td>
        <td><%= libr_usuario.password %></td>
        <td><%= link_to 'Show', libr_usuario %></td>
        <td><%= link_to 'Edit', edit_libr_usuario_path(libr_usuario) %></td>
        <td><%= link_to 'Destroy', libr_usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Libr usuario', new_libr_usuario_path %>

app/views/libr_usuarios/new.html.erb
<div id="cabecera">

	<div id="cabsup">
		<div id="logo">
			<br>
		<IMG SRC="/logo.png" ALT="La primera biblioteca física p2p" WIDTH=300 HEIGHT=100% >

		</div>

		<div id="login">
		<br>
		<%= link_to 'Accede a tu cuenta', login_path %>
		<%= link_to 'Regístrate', new_libr_usuario_path %>
		</div>
	</div>


	<div id="menu">

	 <ul>
	    <li><%= link_to 'Inicio', root_path %></li>
	    <li><%= link_to '¿Cómo funciona?', funcionamiento_path %></li>
	    <li><%= link_to 'Preguntas Frecuentes', preguntas_path %></li>
	    <li><%= link_to 'Nuestros principios', principios_path %></li>
	    <li><%= link_to 'Contacto', contacto_path %></li>
	 </ul>

	</div>

</div>




<br>
<br>
<br>
<div id="principal">

	<div id="princip_izda">
	<center>
    <IMG SRC="/owl-158417.png" ALT="La primera biblioteca física p2p"
     WIDTH=278 HEIGHT=100% ALIGN=middl>
     </center>
	</div>




	<div id="princip_dcha">


<h1>Nuevo Usuario</h1>
<%= render 'form' %>

	</div>

</div>

</body>

app/views/libr_usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @libr_usuario.Nombre %>
</p>

<p>
  <strong>Apellido1:</strong>
  <%= @libr_usuario.Apellido1 %>
</p>

<p>
  <strong>Apellido2:</strong>
  <%= @libr_usuario.Apellido2 %>
</p>

<p>
  <strong>Poblacion:</strong>
  <%= @libr_usuario.poblacion %>
</p>

<p>
  <strong>Email:</strong>
  <%= @libr_usuario.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @libr_usuario.password %>
</p>

<%= link_to 'Edit', edit_libr_usuario_path(@libr_usuario) %> |
<%= link_to 'Back', libr_usuarios_path %>