config/routes.rb
Rails.application.routes.draw do
  get 'libr_rel_amigos/new'

  get 'libr_rel_amigos/create'

  get 'libr_rel_amigos/destroy'

  get 'libr_rel_amigos/update'

  resources :libr_rel_lib_usrs

  resources :libr_usuarios

  resources :libr_libros
    resources :sessions  

  get 'funcionamiento' => 'welcomee#funcionamiento'
  get 'preguntas' => 'welcomee#preguntas'
  get 'principios' => 'welcomee#principios'
  get 'contacto' => 'welcomee#contacto'

  

  get 'login' => 'sessions#new'
  get "log_out" => "sessions#destroy", :as => "log_out"

  get 'portada' => 'portada#inicio'
  get 'contenido' => 'portada#contenido'
  

  get 'libronuevo' => 'portada#libronuevo'

get 'cuentacreada' => 'libr_usuarios#cuentacreada'

  root 'welcomee#index'

end

app/models/libr_rel_lib_usr.rb
class LibrRelLibUsr < ActiveRecord::Base
	belongs_to :libr_libro
	belongs_to :libr_usuario
	validates_presence_of :libr_libro_id
	validates_presence_of :libr_usuario_id
end

app/controllers/libr_rel_lib_usrs_controller.rb
class LibrRelLibUsrsController < ApplicationController
  before_action :set_libr_rel_lib_usr, only: [:show, :edit, :update, :destroy]
  before_action :set_libr_libro

  # GET /libr_rel_lib_usrs
  # GET /libr_rel_lib_usrs.json
  def index
    @libr_rel_lib_usrs = LibrRelLibUsr.all
  end

  # GET /libr_rel_lib_usrs/1
  # GET /libr_rel_lib_usrs/1.json
  def show
  end

  # GET /libr_rel_lib_usrs/new
  def new
    @libr_rel_lib_usr = LibrRelLibUsr.new
  end

  # GET /libr_rel_lib_usrs/1/edit
  def edit
  end

  # POST /libr_rel_lib_usrs
  # POST /libr_rel_lib_usrs.json
  def create
    @libr_rel_lib_usr = LibrRelLibUsr.new(libr_rel_lib_usr_params)

    respond_to do |format|
      if @libr_rel_lib_usr.save
        format.html { redirect_to @libr_rel_lib_usr, notice: 'Libr rel lib usr was successfully created.' }
        format.json { render :show, status: :created, location: @libr_rel_lib_usr }
      else
        format.html { render :new }
        format.json { render json: @libr_rel_lib_usr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libr_rel_lib_usrs/1
  # PATCH/PUT /libr_rel_lib_usrs/1.json
  def update
    respond_to do |format|
      if @libr_rel_lib_usr.update(libr_rel_lib_usr_params)
        format.html { redirect_to @libr_rel_lib_usr, notice: 'Libr rel lib usr was successfully updated.' }
        format.json { render :show, status: :ok, location: @libr_rel_lib_usr }
      else
        format.html { render :edit }
        format.json { render json: @libr_rel_lib_usr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libr_rel_lib_usrs/1
  # DELETE /libr_rel_lib_usrs/1.json
  def destroy
    @libr_rel_lib_usr.destroy
    respond_to do |format|
      format.html { redirect_to libr_rel_lib_usrs_url, notice: 'Libr rel lib usr was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_libr_rel_lib_usr
      @libr_rel_lib_usr = LibrRelLibUsr.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def libr_rel_lib_usr_params
      params.require(:libr_rel_lib_usr).permit(:libr_libro_id, :libr_usuario_id, :ubicacion, :otro)
    end

    def set_libr_libro
      @libr_libro = LibrLibro.all
    end



end

app/helpers/libr_rel_lib_usrs_helper.rb
module LibrRelLibUsrsHelper
end

app/views/libr_rel_lib_usrs/_form.html.erb
<%= form_for(@libr_rel_lib_usr) do |f| %>
  <% if @libr_rel_lib_usr.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@libr_rel_lib_usr.errors.count, "error") %> prohibited this libr_rel_lib_usr from being saved:</h2>

      <ul>
      <% @libr_rel_lib_usr.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :libr_libro_id %><br>
    <%= f.number_field :libr_libro_id %>
  </div>
  <div class="field">
    <%= f.label :libr_usuario_id %><br>
    <%= f.number_field :libr_usuario_id %>
  </div>
  <div class="field">
    <%= f.label :ubicacion %><br>
    <%= f.text_field :ubicacion %>
  </div>
  <div class="field">
    <%= f.label :otro %><br>
    <%= f.text_field :otro %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= form_for(@libr_libro) do |f| %>
  <% if @libr_libro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@libr_libro.errors.count, "error") %> prohibited this libr_libro from being saved:</h2>

      <ul>
      <% @libr_libro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :autor %><br>
    <%= f.text_field :autor %>
  </div>
  <div class="field">
    <%= f.label :editorial %><br>
    <%= f.text_field :editorial %>
  </div>
  <div class="field">
    <%= f.label :comentario %><br>
    <%= f.text_field :comentario %>
  </div>
  <div class="field">
    <%= f.label :otro1 %><br>
    <%= f.text_field :otro1 %>
  </div>
  <div class="field">
    <%= f.label :otro2 %><br>
    <%= f.text_field :otro2 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/libr_rel_lib_usrs/edit.html.erb
<h1>Editing Libr Rel Lib Usr</h1>

<%= render 'form' %>

<%= link_to 'Show', @libr_rel_lib_usr %> |
<%= link_to 'Back', libr_rel_lib_usrs_path %>

app/views/libr_rel_lib_usrs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Libr Rel Lib Usrs</h1>

<table>
  <thead>
    <tr>
      <th>Libr libro</th>
      <th>Libr usuario</th>
      <th>Ubicacion</th>
      <th>Otro</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @libr_rel_lib_usrs.each do |libr_rel_lib_usr| %>
      <tr>
        <td><%= libr_rel_lib_usr.libr_libro_id %></td>
        <td><%= libr_rel_lib_usr.libr_usuario_id %></td>
        <td><%= libr_rel_lib_usr.ubicacion %></td>
        <td><%= libr_rel_lib_usr.otro %></td>
        <td><%= link_to 'Show', libr_rel_lib_usr %></td>
        <td><%= link_to 'Edit', edit_libr_rel_lib_usr_path(libr_rel_lib_usr) %></td>
        <td><%= link_to 'Destroy', libr_rel_lib_usr, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Libr rel lib usr', new_libr_rel_lib_usr_path %>

app/views/libr_rel_lib_usrs/new.html.erb
<h1>New Libr Rel Lib Usr</h1>

<%= render 'form' %>

<%= link_to 'Back', libr_rel_lib_usrs_path %>

app/views/libr_rel_lib_usrs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Libr libro:</strong>
  <%= @libr_rel_lib_usr.libr_libro_id %>
</p>

<p>
  <strong>Libr usuario:</strong>
  <%= @libr_rel_lib_usr.libr_usuario_id %>
</p>

<p>
  <strong>Ubicacion:</strong>
  <%= @libr_rel_lib_usr.ubicacion %>
</p>

<p>
  <strong>Otro:</strong>
  <%= @libr_rel_lib_usr.otro %>
</p>

<%= link_to 'Edit', edit_libr_rel_lib_usr_path(@libr_rel_lib_usr) %> |
<%= link_to 'Back', libr_rel_lib_usrs_path %>