config/routes.rb
Rails.application.routes.draw do
  get 'libr_rel_amigos/new'

  get 'libr_rel_amigos/create'

  get 'libr_rel_amigos/destroy'

  get 'libr_rel_amigos/update'

  resources :libr_rel_lib_usrs

  resources :libr_usuarios

  resources :libr_libros
    resources :sessions  

  get 'funcionamiento' => 'welcomee#funcionamiento'
  get 'preguntas' => 'welcomee#preguntas'
  get 'principios' => 'welcomee#principios'
  get 'contacto' => 'welcomee#contacto'

  

  get 'login' => 'sessions#new'
  get "log_out" => "sessions#destroy", :as => "log_out"

  get 'portada' => 'portada#inicio'
  get 'contenido' => 'portada#contenido'
  

  get 'libronuevo' => 'portada#libronuevo'

get 'cuentacreada' => 'libr_usuarios#cuentacreada'

  root 'welcomee#index'

end

app/controllers/portada_controller.rb
class PortadaController < ApplicationController
before_action :set_libr_libro, :set_libr_rel_lib_usr, :show_amistades, :set_libr_nuevo

#Muestra en portada los libros del usuario.
 def set_libr_libro
          current_user2 ||= LibrUsuario.find(session[:user_id]) if session[:user_id]

    idusuario = current_user2.id

    algunlibro = LibrRelLibUsr.find_by(libr_usuario_id: idusuario)
    if algunlibro

       concatenar="inner join libr_rel_lib_usrs on
                                     libr_rel_lib_usrs.libr_libro_id = libr_libros.id
                                     where libr_usuario_id = " + idusuario.to_s 
      @libr_libros = LibrLibro.joins(concatenar)
  
    else
      @libr_libros = "sinlibros"
    end


  end

  def set_libr_rel_lib_usr
      @libr_rel_lib_usr = LibrRelLibUsr.all
  end



  def show_amistades
    current_user2 ||= LibrUsuario.find(session[:user_id]) if session[:user_id]
     idusuario = current_user2.id

    amistades = LibrRelAmigo.find_by(id: idusuario)
      misamigos = amistades.amigos_string
        if misamigos
          kk= "id in ( "+ misamigos + ")"
          @amigos = LibrUsuario.where(kk)
        else
          @amigos = "Sin amigos"
        end
    rescue 
      @amigos = "Sin amigos"

  end




     def set_libr_nuevo


      @libr_nuevo = LibrLibro.all
     end

    # Never trust parameters from the scary internet, only allow the white list through.
   # def libr_libro_params
   #   params.require(:libr_libro).permit(:titulo, :autor, :editorial, :comentario, :otro1, :otro2)
   # end

end

app/helpers/portada_helper.rb
module PortadaHelper
end

app/views/portada/_amistades.html.erb
<table>
	<thead>
		<tr>
		<th>Nombre</th>
		<th>Apellido1</th>
		<th>Apellido2</th>
		<th>Población</th>
		<th>email</th>
		<th colspan="3"></th>
		</tr>
	<hr>
	</thead>

	<tbody>
		<% @amigos.each do |amigo| %>
		<tr>
		<td><%= amigo.Nombre %></td>
		<td><%= amigo.Apellido1 %></td>
		<td><%= amigo.Apellido2 %></td>
		<td><%= amigo.poblacion %></td>
		<td><%= amigo.email %></td>

		</tr>

		<% end %>
	</tbody>
</table>



<hr>

app/views/portada/_form_new_libro.html.erb
<%= form_for(@libr_nuevo) do |f| %>
  <% if @libr_nuevo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@libr_nuevo.errors.count, "error") %> prohibited this libr_nuevo from being saved:</h2>

      <ul>
      <% @libr_nuevo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :autor %><br>
    <%= f.text_field :autor %>
  </div>
  <div class="field">
    <%= f.label :editorial %><br>
    <%= f.text_field :editorial %>
  </div>
  <div class="field">
    <%= f.label :comentario %><br>
    <%= f.text_field :comentario %>
  </div>
  <div class="field">
    <%= f.label :otro1 %><br>
    <%= f.text_field :otro1 %>
  </div>
  <div class="field">
    <%= f.label :otro2 %><br>
    <%= f.text_field :otro2 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/portada/_mislibros.html.erb
		            <table>
					  <thead>
					    <tr>
					      <th>Titulo</th>
					      <th>Autor</th>
					      <th>Editorial</th>
					      <th>Comentario</th>
					      <th colspan="3"></th>
					     
					    </tr>
					     <hr>
					  </thead>


					  <tbody>
					    <% @libr_libros.each do |libr_libro| %>
					      <tr>
					        <td><%= libr_libro.titulo %></td>
					        <td><%= libr_libro.autor %></td>
					        <td><%= libr_libro.editorial %></td>
					        <td><%= libr_libro.comentario %></td>
					        <td><%= link_to 'Show', libr_libro %></td>
					        <td><%= link_to 'Edit', edit_libr_libro_path(libr_libro) %></td>
					        <td><%= link_to 'Destroy', libr_libro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
					      </tr>

					    <% end %>
					  </tbody>
					</table>

					 <hr>
			     

app/views/portada/inicio.html.erb
<body>
	<div id="barraconfig">
		
		<div id="confizda">
			<IMG SRC="/logo_inv.png" ALT="LibreTeca_Logo" WIDTH=200 HEIGHT=100% >
		</div>

		<div id="confdcha">
			 <ul id="lin_confdcha">	
			<%= link_to image_tag("/IcoUserSett.png", size: "35x35"), log_out_path %>
			<%= link_to image_tag("/IcoBooksSett.png", size: "35x35"), log_out_path %>
	        <%= link_to image_tag("/log_out2.png", size: "40x35"), log_out_path %>

			 </ul>
		</div>
	</div>






	<div id="pagprincipal">

		<h2>Bienvenido <%= current_user.Nombre %>.</h2>
		<p id="notice"><%= notice %></p>







		<div class="tabs">
		    <!--pestaña 1 activa por defecto-->
		    <div class="tab">
		    	<!--input determina la pestaña activa.-->
		        <input type="radio" id="tab-1" name="tab-group-1" checked>
		        <label for="tab-1">Mis libros</label>
		        <!--contenido de la pestaña 1-->
		        <div class="content">


		        <%= link_to 'Añadir libro nuevo',  libronuevo_path  %></td>

		            <%if @libr_libros == "sinlibros"%>
		            	 Aún no has añadido ningún item. Comparte, no seas rata.
		            <%else%>
		            	
		            <%=	render "mislibros" %>
		         	<%end %>




		        </div>
		    </div>








		    <!-- pestaña 2-->
		    <div class="tab">
		        <input type="radio" id="tab-2" name="tab-group-1">
		        <label for="tab-2"> Mis contactos</label>
		        <div class="content">
		            <!--contenido de la pestaña 2-->


		            <%if @amigos == "Sin amigos"%>
		            	 Aún no has añadido ningún amigo. Supongo que cuando cree la opción podrás hacerlo.
		            <%else%>
		            	
		            <%=	render "amistades" %>
		         	<%end %>



			            






		 
		        </div>
		    </div>










		    <!-- pestaña 3-->
		    <div class="tab">
		        <input type="radio" id="tab-3" name="tab-group-1">
		        <label for="tab-3">Mis búsquedas</label>
		        <!--contenido de la pestaña 3-->
		        <div class="content">
		            Aquí va un formulario con las opciones de búsquedas y una tabla con los resultados a continuación.



		        </div>
		    </div>

		</div>


	</div>



		<table>
		  <thead>
		    <tr>
		      <th>Nombre</th>
		      <th>Apellido1</th>
		      <th>Apellido2</th>
		      <th>Poblacion</th>
		      <th>Email</th>
		      <th>Password</th>
		      <th colspan="3"></th>
		    </tr>
		  </thead>

		  <tbody>
		      <tr>
		        <td><%= current_user.Nombre %></td>
		        <td><%= current_user.Apellido1 %></td>
		        <td><%= current_user.Apellido2 %></td>
		        <td><%= current_user.poblacion %></td>
		        <td><%= current_user.email %></td>
		        <td><%= current_user.password %></td>

		      </tr>
		  </tbody>
		</table>

		<br>

app/views/portada/libronuevo.html.erb
<body>
	<div id="barraconfig">
		
		<div id="confizda">
			<IMG SRC="/logo_inv.png" ALT="LibreTeca_Logo" WIDTH=200 HEIGHT=100% >
		</div>

		<div id="confdcha">
			 <ul id="lin_confdcha">	
			<%= link_to image_tag("/IcoUserSett.png", size: "35x35"), log_out_path %>
			<%= link_to image_tag("/IcoBooksSett.png", size: "35x35"), log_out_path %>
	        <%= link_to image_tag("/log_out2.png", size: "40x35"), log_out_path %>

			 </ul>
		</div>
	</div>






	<div id="pagprincipal">

		<h2>Bienvenido <%= current_user.Nombre %>.</h2>
		<p id="notice"><%= notice %></p>







		<div class="tabs">
		    <!--pestaña 1 activa por defecto-->
		    <div class="tab">
		    	<!--input determina la pestaña activa.-->
		        <input type="radio" id="tab-1" name="tab-group-1" checked>
		        <label for="tab-1">Mis libros</label>
		        <!--contenido de la pestaña 1-->
		        <div class="content">



					<h1>New Libr Libro</h1>

					<%= render 'form_new_libro' %>

					<%= link_to 'Back', portada_path %>





		        </div>
		    </div>








		    <!-- pestaña 2-->
		    <div class="tab">
		        <input type="radio" id="tab-2" name="tab-group-1">
		        <label for="tab-2"> Mis contactos</label>
		        <div class="content">
		            <!--contenido de la pestaña 2-->


		            <%if @amigos == "Sin amigos"%>
		            	 Aún no has añadido ningún amigo. Supongo que cuando cree la opción podrás hacerlo.
		            <%else%>
		            	
		            <%=	render "amistades" %>
		         	<%end %>



			            






		 
		        </div>
		    </div>










		    <!-- pestaña 3-->
		    <div class="tab">
		        <input type="radio" id="tab-3" name="tab-group-1">
		        <label for="tab-3">Mis búsquedas</label>
		        <!--contenido de la pestaña 3-->
		        <div class="content">
		            Aquí va un formulario con las opciones de búsquedas y una tabla con los resultados a continuación.



		        </div>
		    </div>

		</div>


	</div>



		<table>
		  <thead>
		    <tr>
		      <th>Nombre</th>
		      <th>Apellido1</th>
		      <th>Apellido2</th>
		      <th>Poblacion</th>
		      <th>Email</th>
		      <th>Password</th>
		      <th colspan="3"></th>
		    </tr>
		  </thead>

		  <tbody>
		      <tr>
		        <td><%= current_user.Nombre %></td>
		        <td><%= current_user.Apellido1 %></td>
		        <td><%= current_user.Apellido2 %></td>
		        <td><%= current_user.poblacion %></td>
		        <td><%= current_user.email %></td>
		        <td><%= current_user.password %></td>

		      </tr>
		  </tbody>
		</table>

		<br>